#:kivy 2.3.0

<MainGrid>:   

    output: output

    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 1

            TextInput:
                multiline: False

            Label:
                id: output
                text: "Test"

        GridLayout:
            cols: 2
            Button:
                text: 'Add Plant'
                on_press: root.say_hello()
            Button:
                text: 'Show Tasks'
                on_press: root.say_hello()