#:kivy 2.3.0

WindowManager:
    AddPlant:
    ShowTasks:
    ShowPlants:

<AddPlant>:
    name: "AddPlants"
    plantInput: plantInput
    nameTextInput: name
    lTWTextInput: lTW
    heightTextInput: height
    
    GridLayout:
        id: addPlantMainGrid
        cols: 1

        GridLayout:
            id: plantInput
            cols: 2

            Label:
                text: "Name: "
            TextInput:
                id: name
                multiline: False
            
            Label:
                text: "Height: "
            TextInput:
                id: height
                multiline: False

            Label:
                text: "last time watered (days ago): "
            TextInput:
                id: lTW
                multiline: False
    
        MenuButtons:
            id: mButtonsAddPlant
                    
<ShowPLants>:
    name: "Plants"
    plantsGrid: plantsGrid

    GridLayout:
        id: showPlantsMainGrid
        cols: 1

        GridLayout:
            id: plantsGrid
            cols: 1
            rows: 3
            size_hint: (1, 1)
            padding: [showPlantsMainGrid.width*0.1, 0]

        MenuButtons:
            id: mButtonsPlants


<ShowTasks>:
    name: "Tasks"
    outputLabel: output

    GridLayout:
        id: showTasksMainGrid
        cols: 1

        Label:
            id: output
        
        MenuButtons:
            id: mButtonsTasks

<RoundCorneredButton>:
    canvas:
        Color:
            rgb: (0, 1, 0, 0.1) if self.state == 'normal' else (0, 250, 0, 0.5)
        RoundedRectangle:
            size: (self.size)
            pos: (self.pos)
            radius: [100, 20]


<MenuButtons>:
    size_hint: (1, 0.3)
    cols: 3
    spacing: 10
    RoundCorneredButton:
        text: "Show Tasks"
        on_release:
            app.root.current = "Tasks"
    RoundCorneredButton:
        text: "Show Plants"
        on_release:
            app.root.current = "Plants"
    RoundCorneredButton:
        text: "Add Plants"
        on_release:
            app.root.current = "AddPlants"
