#:kivy 2.3.0

#color-code:
#   green: #78AA6E
#   brown: #CC957C
#   purple: #726FAB
#   dark_green: #243321

WindowManager:
    id: WM
    AddPlant:
    ShowTasks:
    ShowPlants:

<AddPlant>:
    name: "AddPlant"
    plantInput: plantInput
    nameTextInput: name
    lTWTextInput: lTW
    heightTextInput: height
    
    GridLayout:
        id: addPlantMainGrid
        cols: 1

        GridLayout:
            id: plantInput
            cols: 2

            Label:
                text: "Name: "
            TextInput:
                id: name
                multiline: False
            
            Label:
                text: "Height: "
            TextInput:
                id: height
                multiline: False

            Label:
                text: "last time watered (days ago): "
            TextInput:
                id: lTW
                multiline: False
    
        MenuButtons:
            id: mButtonsAddPlant
                    
<ShowPlants>:
    name: "Plants"
    plantsGrid: plantsGrid

    GridLayout:
        id: showPlantsMainGrid
        cols: 1
        ScrollView:
            do_scroll_x: False
            size_hint: (1,1)
            GridLayout:
                id: plantsGrid
                cols: 1
                size_hint: (1, 1)
                spacing: self.height*0.01
                padding: [showPlantsMainGrid.width*0.1, 0]
                canvas.before:
                    Color:
                        rgb: kivy.utils.get_color_from_hex("#243321")
                    Rectangle:
                        size: self.size
                        pos: self.pos

        MenuButtons:
            id: mButtonsPlants

<SPRow>:
    cols: 2
    spacing: self.width*0.01

<SPLabel>:
    disabled: True
    disabled_color: 255,255,255,1
    background_disabled_normal: ""
    halign: "center"
    size_hint: (0.7, 1)
    background_color: kivy.utils.get_color_from_hex("#78AA6E")

<SPRmvButton>:
    size_hint: (0.3, 1)
    background_color: kivy.utils.get_color_from_hex("#CC957C")
    Image:
        source: "data/img/icons/cross.png"
        center_x: self.parent.center_x
        center_y: self.parent.center_y
        size: (self.texture_size[0]*0.1, self.texture_size[1]*0.1)

<ShowTasks>:
    name: "Tasks"
    tasksGrid: tasksGrid

    GridLayout:
        id: showTasksMainGrid
        cols: 1

        GridLayout:
            id: tasksGrid
            cols: 1
            size_hint: (1,1)
            spacing: self.height*0.01
            padding: [showTasksMainGrid.width*0.1, 0]
            canvas.before:
                Color:
                    rgb: kivy.utils.get_color_from_hex("#243321")
                Rectangle:
                    size: self.size
                    pos: self.pos 
        
        MenuButtons:
            id: mButtonsTasks

<STRow>:
    cols: 2
    spacing: self.width*0.01

<STLabel>:
    disabled: True
    disabled_color: 255,255,255,1
    background_disabled_normal: ""
    halign: "center"
    background_color: kivy.utils.get_color_from_hex("#78AA6E")

<MenuButtons>:
    size_hint: (1, 0.2)
    cols: 3
    spacing: self.width*0.01
    padding: self.width*0.01
    canvas.before:
        Color:
            rgb: kivy.utils.get_color_from_hex('#243321')
        Rectangle:
            size: self.size
            pos: self.pos
    MenuButton:
        on_release:
            app.root.transition.direction = "right"
            app.root.current = "Plants"
        MenuBtnImage:
            source: "data/img/icons/plants.png"
        MenuBtnLabel:
            text: "Show Plants"

    MenuButton:
        on_release:
            if app.root.current == "Plants": app.root.transition.direction = "left" 
            else: app.root.transition.direction = "right"
            app.root.current = "Tasks"        
        MenuBtnImage:
            source: "data/img/icons/tasks.png"
        MenuBtnLabel:
            text: "Show Tasks"

    MenuButton:
        on_release:
            app.root.transition.direction = "left"
            app.root.current = "AddPlant"
        MenuBtnImage:
            source: "data/img/icons/addPlant.png"
        MenuBtnLabel:
            text: "Add Plant"

<MenuButton>:
    background_color: kivy.utils.get_color_from_hex("#CC957C")

<MenuBtnImage>:
    center_x: self.parent.center_x
    center_y: self.parent.center_y*1.2
    size: (self.texture_size[0]*0.1, self.texture_size[1]*0.1)
<MenuBtnLabel>:
    text_size: (self.parent.width, None)
    color: (0,0,0,1)
    halign: "center"
    center_x: self.parent.center_x
    center_y: self.parent.center_y*0.6
